export const get_cameras = [
    {
      id: 1,
      name: "场地A1摄像头",
      description: "hikvision V1 in ground A1",
      ip: "192.168.1.5",
      state: "online",
      start_time: "2024-06-08 12:24:11",
      src:"http://vjs.zencdn.net/v/oceans.mp4",
      regions: [
        {
          id: "2024010123112",
          name: "场地A1禁止吸烟区",
          description: "",
          rect: true,
          points: [
            { x: 100, y: 100 },
            { x: 200, y: 200 },
            { x: 300, y: 300 },
            { x: 400, y: 400 },
            { x: 500, y: 500 },
            { x: 600, y: 600 },
            { x: 700, y: 700 },
            { x: 800, y: 800 },
            { x: 900, y: 900 },
            { x: 1000, y: 1000 },
          ],
          type_detects: [1, 3, 5],
          state: "active",
          events: [
            {
              id: "202401020320",
              description: "禁止吸烟",
              type: 5,
              time: "2024-06-08 12:24:11",
              photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              thumb: "hgfeliqhdlwfqhliwdqwd",
              detect_photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
            },
            {
              id: "202401020323",
              description: "人员未到岗",
              type: 1,
              time: "2024-06-09 12:33:11",
              photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              thumb: "hgfeliqhdlwfqhliwdqwd",
              detect_photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
            },
            {
              id: "202401020335",
              description: "禁止吸烟",
              type: 5,
              time: "2024-06-08 12:24:11",
              photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              thumb: "hgfeliqhdlwfqhliwdqwd",
              detect_photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
            },
          ],
        },
      ],
    },
    {
      id: 2,
      name: "场地B1摄像头",
      description: "hikvision V1 in ground B1",
      ip: "192.168.1.6",
      state: "offline",
      start_time: "2024-06-08 12:25:11",
      src:"http://vjs.zencdn.net/v/oceans.mp4",
      regions: [
        {
          id: "2024010223113",
          name: "场地B1危险区",
          description: "",
          rect: false,
          points: [
            { x: 150, y: 150 },
            { x: 250, y: 250 },
            { x: 350, y: 350 },
            { x: 450, y: 450 },
            { x: 550, y: 550 },
            { x: 650, y: 650 },
            { x: 750, y: 750 },
            { x: 850, y: 850 },
            { x: 950, y: 950 },
            { x: 1050, y: 1050 },
          ],
          type_detects: [2, 4, 6],
          state: "active",
          events: [
            {
              id: "202401030321",
              description: "入侵检测",
              type: 2,
              time: "2024-06-09 13:24:11",
              photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              thumb: "gjifelfjlewfhqlefwqf",
              detect_photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
            },
            {
              id: "202401030324",
              description: "跌倒检测",
              type: 4,
              time: "2024-06-10 14:33:11",
              photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              thumb: "giqhlefjqlwehfliqehfw",
              detect_photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
            },
          ],
        },
      ],
    },
    {
      id: 3,
      name: "场地C1摄像头",
      description: "hikvision V1 in ground C1",
      ip: "192.168.1.7",
      state: "online",
      start_time: "2024-06-08 12:26:11",
      src:"http://vjs.zencdn.net/v/oceans.mp4",
      regions: [
        {
          id: "2024010323114",
          name: "场地C1安全区",
          description: "",
          rect: true,
          points: [
            { x: 120, y: 120 },
            { x: 220, y: 220 },
            { x: 320, y: 320 },
            { x: 420, y: 420 },
            { x: 520, y: 520 },
            { x: 620, y: 620 },
            { x: 720, y: 720 },
            { x: 820, y: 820 },
            { x: 920, y: 920 },
            { x: 1020, y: 1020 },
          ],
          type_detects: [7, 8],
          state: "active",
          events: [
            {
              id: "202401040322",
              description: "设备状态异常",
              type: 7,
              time: "2024-06-08 15:24:11",
              photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              thumb: "hfklwefhqlwekfhqlewf",
              detect_photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
            },
            {
              id: "202401040325",
              description: "未穿反光衣",
              type: 8,
              time: "2024-06-09 16:33:11",
              photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              thumb: "giqlehflqhewfhlqwhef",
              detect_photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
            },
          ],
        },
      ],
    },
    {
      id: 4,
      name: "场地D1摄像头",
      description: "hikvision V1 in ground D1",
      ip: "192.168.1.8",
      state: "deleted",
      start_time: "2024-06-08 12:27:11",
      src:"http://vjs.zencdn.net/v/oceans.mp4",
      regions: [
        {
          id: "2024010423115",
          name: "场地D1检测区",
          description: "",
          rect: false,
          points: [
            { x: 130, y: 130 },
            { x: 230, y: 230 },
            { x: 330, y: 330 },
            { x: 430, y: 430 },
          ],
          type_detects: [9, 10],
          state: "inactive",
          events: [
            {
              id: "202401050323",
              description: "打架检测",
              type: 9,
              time: "2024-06-08 17:24:11",
              photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              thumb: "hfqlewhflqwefhqwlef",
              detect_photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
            },
            {
              id: "202401050326",
              description: "抽烟检测",
              type: 10,
              time: "2024-06-09 18:33:11",
              photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              thumb: "giqhlehfqlwehflqwhf",
              detect_photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
            },
          ],
        },
      ],
    },
];

export const detect_types = [
  {
    id: 1,
    name: "人员核查",
    description: "区域计数，基于图片核查到岗",
  },
  {
    id: 2,
    name: "电子围栏",
    description: "禁入区域入侵检测",
  },
  {
    id: 3,
    name: "安全帽检测",
    description: "",
  },
  {
    id: 4,
    name: "跌倒检测",
    description: "",
  },
  {
    id: 5,
    name: "烟火检测",
    description: "",
  },
  {
    id: 6,
    name: "积水检测",
    description: "",
  },
  {
    id: 7,
    name: "设备状态检测",
    description: "柜锁状态，定制",
  },
  {
    id: 8,
    name: "反光衣检测",
    description: "",
  },
  {
    id: 9,
    name: "打架检测",
    description: "附加",
  },
  {
    id: 10,
    name: "抽烟检测",
    description: "附加",
  },
];

