export const get_cameras = [
  {
    id: 1,
    name: "场地A1摄像头",
    description: "hikvision V1 in ground A1",
    ip: "192.168.1.5",
    state: "online",
    start_time: "2024-06-08 12:24:11",
    src: "http://vjs.zencdn.net/v/oceans.mp4",
    regions: [
      {
        id: "2024010123112",
        name: "场地A1禁止吸烟区",
        description: "",
        shape: {
          type: "polygon",
          data: [
            { x: 718, y: 88 },
            { x: 904, y: 94 },
            { x: 879, y: 214 },
            { x: 730, y: 218 },
            { x: 718, y: 88 },
          ],
        },
        type_detects: [1, 3, 5],
        state: "active",
        events: [
          {
            id: "202401020320",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event1.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020323",
            description: "人员未到岗",
            type: 1,
            time: "2024-06-09 12:33:11",
            photo: "./images/event2.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020335",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event3.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020341",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event1.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020352",
            description: "人员未到岗",
            type: 1,
            time: "2024-06-09 12:33:11",
            photo: "./images/event2.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020363",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event3.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
        ],
      },
      {
        id: "2024010123112",
        name: "场地A1禁止吸烟区",
        description: "",
        shape: {
          type: "polygon",
          data: [
            { x: 87, y: 91 },
            { x: 417, y: 88 },
            { x: 381, y: 438 },
            { x: 75, y: 408 },
            { x: 102, y: 241 },
            { x: 87, y: 91 },
          ],
        },
        type_detects: [1, 3, 5],
        state: "active",
        events: [
          {
            id: "202401020320",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event1.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020323",
            description: "人员未到岗",
            type: 1,
            time: "2024-06-09 12:33:11",
            photo: "./images/event2.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020335",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event3.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020341",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event1.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020352",
            description: "人员未到岗",
            type: 1,
            time: "2024-06-09 12:33:11",
            photo: "./images/event2.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020363",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event3.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
        ],
      },
      {
        id: "2024010123112",
        name: "场地A1禁止吸烟区",
        description: "",
        shape: {
          type: "line",
          data: [
            { start: { x: 461, y: 482 }, end: { x: 640, y: 337 } },
            { start: { x: 445, y: 327 }, end: { x: 628, y: 459 } },
          ],
        },
        type_detects: [1, 3, 5],
        state: "active",
        events: [
          {
            id: "202401020320",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event1.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020323",
            description: "人员未到岗",
            type: 1,
            time: "2024-06-09 12:33:11",
            photo: "./images/event2.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020335",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event3.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020341",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event1.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020352",
            description: "人员未到岗",
            type: 1,
            time: "2024-06-09 12:33:11",
            photo: "./images/event2.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020363",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event3.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
        ],
      },
    ],
  },
  {
    id: 2,
    name: "场地A2摄像头",
    description: "hikvision V1 in ground A2",
    ip: "192.168.1.6",
    state: "online",
    start_time: "2024-06-08 12:24:11",
    src: "http://vjs.zencdn.net/v/oceans.mp4",
    regions: [
      {
        id: "2024010123112",
        name: "场地A1禁止吸烟区",
        description: "",
        shape: {
          type: "polygon",
          data: [
            { x: 718, y: 88 },
            { x: 904, y: 94 },
            { x: 879, y: 214 },
            { x: 730, y: 218 },
            { x: 718, y: 88 },
          ],
        },
        type_detects: [1, 3, 5],
        state: "active",
        events: [
          {
            id: "202401020320",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event1.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020323",
            description: "人员未到岗",
            type: 1,
            time: "2024-06-09 12:33:11",
            photo: "./images/event2.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020335",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event3.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020341",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event1.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020352",
            description: "人员未到岗",
            type: 1,
            time: "2024-06-09 12:33:11",
            photo: "./images/event2.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020363",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event3.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
        ],
      },
      {
        id: "2024010123112",
        name: "场地A1禁止吸烟区",
        description: "",
        shape: {
          type: "polygon",
          data: [
            { x: 87, y: 91 },
            { x: 417, y: 88 },
            { x: 381, y: 438 },
            { x: 75, y: 408 },
            { x: 102, y: 241 },
            { x: 87, y: 91 },
          ],
        },
        type_detects: [1, 3, 5],
        state: "active",
        events: [
          {
            id: "202401020320",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event1.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020323",
            description: "人员未到岗",
            type: 1,
            time: "2024-06-09 12:33:11",
            photo: "./images/event2.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020335",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event3.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020341",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event1.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020352",
            description: "人员未到岗",
            type: 1,
            time: "2024-06-09 12:33:11",
            photo: "./images/event2.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020363",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event3.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
        ],
      },
      {
        id: "2024010123112",
        name: "场地A1禁止吸烟区",
        description: "",
        shape: {
          type: "line",
          data: [
            { start: { x: 461, y: 482 }, end: { x: 640, y: 337 } },
            { start: { x: 445, y: 327 }, end: { x: 628, y: 459 } },
          ],
        },
        type_detects: [1, 3, 5],
        state: "active",
        events: [
          {
            id: "202401020320",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event1.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020323",
            description: "人员未到岗",
            type: 1,
            time: "2024-06-09 12:33:11",
            photo: "./images/event2.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020335",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event3.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020341",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event1.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020352",
            description: "人员未到岗",
            type: 1,
            time: "2024-06-09 12:33:11",
            photo: "./images/event2.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020363",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event3.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
        ],
      },
    ],
  },
  {
    id: 3,
    name: "场地A3摄像头",
    description: "hikvision V1 in ground A3",
    ip: "192.168.1.5",
    state: "online",
    start_time: "2024-06-08 12:24:11",
    src: "http://vjs.zencdn.net/v/oceans.mp4",
    regions: [
      {
        id: "2024010123112",
        name: "场地A1禁止吸烟区",
        description: "",
        shape: {
          type: "polygon",
          data: [
            { x: 718, y: 88 },
            { x: 904, y: 94 },
            { x: 879, y: 214 },
            { x: 730, y: 218 },
            { x: 718, y: 88 },
          ],
        },
        type_detects: [1, 3, 5],
        state: "active",
        events: [
          {
            id: "202401020320",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event1.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020323",
            description: "人员未到岗",
            type: 1,
            time: "2024-06-09 12:33:11",
            photo: "./images/event2.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020335",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event3.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020341",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event1.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020352",
            description: "人员未到岗",
            type: 1,
            time: "2024-06-09 12:33:11",
            photo: "./images/event2.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020363",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event3.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
        ],
      },
      {
        id: "2024010123112",
        name: "场地A1禁止吸烟区",
        description: "",
        shape: {
          type: "polygon",
          data: [
            { x: 87, y: 91 },
            { x: 417, y: 88 },
            { x: 381, y: 438 },
            { x: 75, y: 408 },
            { x: 102, y: 241 },
            { x: 87, y: 91 },
          ],
        },
        type_detects: [1, 3, 5],
        state: "active",
        events: [
          {
            id: "202401020320",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event1.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020323",
            description: "人员未到岗",
            type: 1,
            time: "2024-06-09 12:33:11",
            photo: "./images/event2.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020335",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event3.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020341",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event1.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020352",
            description: "人员未到岗",
            type: 1,
            time: "2024-06-09 12:33:11",
            photo: "./images/event2.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020363",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event3.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
        ],
      },
      {
        id: "2024010123112",
        name: "场地A1禁止吸烟区",
        description: "",
        shape: {
          type: "line",
          data: [
            { start: { x: 461, y: 482 }, end: { x: 640, y: 337 } },
            { start: { x: 445, y: 327 }, end: { x: 628, y: 459 } },
          ],
        },
        type_detects: [1, 3, 5],
        state: "active",
        events: [
          {
            id: "202401020320",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event1.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020323",
            description: "人员未到岗",
            type: 1,
            time: "2024-06-09 12:33:11",
            photo: "./images/event2.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020335",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event3.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020341",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event1.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020352",
            description: "人员未到岗",
            type: 1,
            time: "2024-06-09 12:33:11",
            photo: "./images/event2.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
          {
            id: "202401020363",
            description: "禁止吸烟",
            type: 5,
            time: "2024-06-08 12:24:11",
            photo: "./images/event3.jpg",
            thumb: "hgfeliqhdlwfqhliwdqwd",
            detect_photo:
              "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
            replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
          },
        ],
      },
    ],
  },
];

export const detect_types = [
  {
    id: 1,
    name: "人员核查",
    description: "区域计数，基于图片核查到岗",
  },
  {
    id: 2,
    name: "电子围栏",
    description: "禁入区域入侵检测",
  },
  {
    id: 3,
    name: "安全帽检测",
    description: "",
  },
  {
    id: 4,
    name: "跌倒检测",
    description: "",
  },
  {
    id: 5,
    name: "烟火检测",
    description: "",
  },
  {
    id: 6,
    name: "积水检测",
    description: "",
  },
  {
    id: 7,
    name: "设备状态检测",
    description: "柜锁状态，定制",
  },
  {
    id: 8,
    name: "反光衣检测",
    description: "",
  },
  {
    id: 9,
    name: "打架检测",
    description: "附加",
  },
  {
    id: 10,
    name: "抽烟检测",
    description: "附加",
  },
];
