export const get_cameras = [
    {
      id: 1,
      name: "场地A1摄像头",
      description: "hikvision V1 in ground A1",
      ip: "192.168.1.5",
      state: "online",
      start_time: "2024-06-08 12:24:11",
      src:"http://d2zihajmogu5jn.cloudfront.net/elephantsdream/ed_hd.mp4",
      regions: [
        {
          id: "2024010123112",
          name: "场地A1禁止吸烟区",
          description: "",
          type: "polygon",
          points: [
            { x: 56, y: 24 },
            { x: 122, y: 322 },
            { x: 133, y: 222 },
            { x: 222, y: 233 },
            { x: 133, y: 222 },
            { x: 150, y: 150 },
            { x: 150, y: 150 },
            { x: 100, y: 100 },
          ],
          type_detects: [1, 3, 5],
          state: "active",
          events: [
            {
              id: "202401020320",
              description: "禁止吸烟",
              type: 5,
              time: "2024-06-08 12:24:11",
              photo: "./images/event1.jpg",
              thumb: "hgfeliqhdlwfqhliwdqwd",
              detect_photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
            },
            {
              id: "202401020323",
              description: "人员未到岗",
              type: 1,
              time: "2024-06-09 12:33:11",
              photo: "./images/event2.jpg",
              thumb: "hgfeliqhdlwfqhliwdqwd",
              detect_photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
            },
            {
              id: "202401020335",
              description: "禁止吸烟",
              type: 5,
              time: "2024-06-08 12:24:11",
              photo: "./images/event3.jpg",
              thumb: "hgfeliqhdlwfqhliwdqwd",
              detect_photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
            },
            {
              id: "202401020341",
              description: "禁止吸烟",
              type: 5,
              time: "2024-06-08 12:24:11",
              photo: "./images/event1.jpg",
              thumb: "hgfeliqhdlwfqhliwdqwd",
              detect_photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
            },
            {
              id: "202401020352",
              description: "人员未到岗",
              type: 1,
              time: "2024-06-09 12:33:11",
              photo: "./images/event2.jpg",
              thumb: "hgfeliqhdlwfqhliwdqwd",
              detect_photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
            },
            {
              id: "202401020363",
              description: "禁止吸烟",
              type: 5,
              time: "2024-06-08 12:24:11",
              photo: "./images/event3.jpg",
              thumb: "hgfeliqhdlwfqhliwdqwd",
              detect_photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
            },
          ],
        },
      ],
    },
    {
      id: 2,
      name: "场地B1摄像头",
      description: "hikvision V1 in ground B1",
      ip: "192.168.1.6",
      state: "offline",
      start_time: "2024-06-08 12:25:11",
      src:"http://media.w3.org/2010/05/sintel/trailer_hd.mp4",
      regions: [
        {
          id: "2024010223113",
          name: "场地B1危险区",
          description: "",
          type: "line",
          points: [
            { x: 150, y: 150 },
            { x: 250, y: 250 },
            { x: 350, y: 350 },
            { x: 450, y: 450 },
          ],
          type_detects: [2, 4, 6],
          state: "active",
          events: [
            {
              id: "202401030321",
              description: "入侵检测",
              type: 2,
              time: "2024-06-09 13:24:11",
              photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              thumb: "gjifelfjlewfhqlefwqf",
              detect_photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
            },
            {
              id: "202401030324",
              description: "跌倒检测",
              type: 4,
              time: "2024-06-10 14:33:11",
              photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              thumb: "giqhlefjqlwehfliqehfw",
              detect_photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
            },
          ],
        },
      ],
    },
    {
      id: 3,
      name: "场地C1摄像头",
      description: "hikvision V1 in ground C1",
      ip: "192.168.1.7",
      state: "online",
      start_time: "2024-06-08 12:26:11",
      src:"http://maoyan.meituan.net/movie/videos/c0bc7bb9d04343beabf516d4448d6284.mp4",
      regions: [
        {
          id: "2024010323114",
          name: "场地C1安全区",
          description: "",
          type: "polygon",
          points: [
            { x: 120, y: 120 },
            { x: 220, y: 220 },
            { x: 320, y: 320 },
            { x: 420, y: 420 },
            { x: 520, y: 520 },
            { x: 620, y: 620 },
            { x: 720, y: 720 },
            { x: 820, y: 820 },
            { x: 920, y: 920 },
            { x: 1020, y: 1020 },
          ],
          type_detects: [7, 8],
          state: "active",
          events: [
            {
              id: "202401040322",
              description: "设备状态异常",
              type: 7,
              time: "2024-06-08 15:24:11",
              photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              thumb: "hfklwefhqlwekfhqlewf",
              detect_photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
            },
            {
              id: "202401040325",
              description: "未穿反光衣",
              type: 8,
              time: "2024-06-09 16:33:11",
              photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              thumb: "giqlehflqhewfhlqwhef",
              detect_photo: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?undefined",
              replay_url: "http://vjs.zencdn.net/v/oceans.mp4",
            },
          ],
        },
      ],
    },
];

export const detect_types = [
  {
    id: 1,
    name: "人员核查",
    description: "区域计数，基于图片核查到岗",
  },
  {
    id: 2,
    name: "电子围栏",
    description: "禁入区域入侵检测",
  },
  {
    id: 3,
    name: "安全帽检测",
    description: "",
  },
  {
    id: 4,
    name: "跌倒检测",
    description: "",
  },
  {
    id: 5,
    name: "烟火检测",
    description: "",
  },
  {
    id: 6,
    name: "积水检测",
    description: "",
  },
  {
    id: 7,
    name: "设备状态检测",
    description: "柜锁状态，定制",
  },
  {
    id: 8,
    name: "反光衣检测",
    description: "",
  },
  {
    id: 9,
    name: "打架检测",
    description: "附加",
  },
  {
    id: 10,
    name: "抽烟检测",
    description: "附加",
  },
];

